#Here is an example of the k8s manifest which is used to deploy an application. when the user tries to hit the service endpoint(http://myservice:3000) it returns 500. 
#Can you analyze the yaml and find the reason?
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my_deployment
spec:
  selector:
    matchLabels:
      type: example
      color: red
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        type: example
        color: red
    spec:
      containers:
      - name: echocolor
        image: reselbob/echocolor:v0.1
        ports:
        - containerPort: 3000
        env:
        - name: COLOR_ECHO_COLOR
          value: RED
        - name: COLOR_ECHO_VERSION
          value: V1
---
apiVersion: v1
kind: Service
metadata:
  name: my_service
spec:
  selector:
    type: example
    color: blue
  ports:
  -
    protocol: TCP
    port: 3000
    targetPort: 5000
  type: NodePort
